dependencies {
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly project(":core:shielded-container-api")
}

if (jakartaAppServer) {
	task updateSPIFile(type: Zip)

	jar {
		finalizedBy updateSPIFile
	}

	updateSPIFile {
		from {
			zipTree(jar.archivePath)
		}
		rename("jakarta.servlet.ServletContainerInitializer", "javax.servlet.ServletContainerInitializer")

		doLast {
			archivePath.renameTo(jar.archivePath)
		}
	}
}