import de.undercouch.gradle.tasks.download.Download

apply plugin: "de.undercouch.download"

task downloadReleasesJson(type: Download)

configurations {
	portalTestSnapshot {
		exclude group: "com.liferay.portal", module: "com.liferay.portal.impl"
		exclude group: "com.liferay.portal", module: "com.liferay.portal.kernel"
	}
}

dependencies {
	compileInclude group: "com.liferay", name: "com.liferay.portal.tools.bundle.support", version: "3.7.5"

	implementation group: "org.slf4j", name: "slf4j-api", version: "2.0.13"
	implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.16.1"
}

downloadReleasesJson {
	dest buildDir
	onlyIfNewer true
	src "https://releases-cdn.liferay.com/releases.json"
}

processResources {
	from downloadReleasesJson
}

updateFileVersions {
	match(/name: "com\.liferay\.release\.info\.util", version: "(\d.+)"/, "../gradle-plugins-workspace/build.gradle")
}