/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type {HeadlessCommerceAdminOrder_v1_0_Account} from './HeadlessCommerceAdminOrder_v1_0_Account';
import type {HeadlessCommerceAdminOrder_v1_0_BillingAddress} from './HeadlessCommerceAdminOrder_v1_0_BillingAddress';
import type {HeadlessCommerceAdminOrder_v1_0_Channel} from './HeadlessCommerceAdminOrder_v1_0_Channel';
import type {HeadlessCommerceAdminOrder_v1_0_OrderItem} from './HeadlessCommerceAdminOrder_v1_0_OrderItem';
import type {HeadlessCommerceAdminOrder_v1_0_ShippingAddress} from './HeadlessCommerceAdminOrder_v1_0_ShippingAddress';
import type {HeadlessCommerceAdminOrder_v1_0_Status} from './HeadlessCommerceAdminOrder_v1_0_Status';
export type HeadlessCommerceAdminOrder_v1_0_Order = {
	'account'?: HeadlessCommerceAdminOrder_v1_0_Account;
	'accountExternalReferenceCode'?: string;
	'accountId'?: number;
	readonly 'actions'?: Record<string, Record<string, string>>;
	'advanceStatus'?: string;
	'billingAddress'?: HeadlessCommerceAdminOrder_v1_0_BillingAddress;
	'billingAddressId'?: number;
	'channel'?: HeadlessCommerceAdminOrder_v1_0_Channel;
	'channelExternalReferenceCode'?: string;
	'channelId': number;
	'couponCode'?: string;
	'createDate'?: string;
	'creatorEmailAddress'?: string;
	'currencyCode': string;
	'customFields'?: Record<string, Record<string, any>>;
	readonly 'deliveryTermDescription'?: string;
	'deliveryTermId'?: number;
	readonly 'deliveryTermName'?: string;
	'externalReferenceCode'?: string;
	'id'?: number;
	'lastPriceUpdateDate'?: string;
	'modifiedDate'?: string;
	'orderDate'?: string;
	'orderItems'?: Array<HeadlessCommerceAdminOrder_v1_0_OrderItem>;
	'orderStatus'?: number;
	'orderStatusInfo'?: HeadlessCommerceAdminOrder_v1_0_Status;
	'orderTypeExternalReferenceCode'?: string;
	'orderTypeId'?: number;
	'paymentMethod'?: string;
	'paymentStatus'?: number;
	'paymentStatusInfo'?: HeadlessCommerceAdminOrder_v1_0_Status;
	readonly 'paymentTermDescription'?: string;
	'paymentTermId'?: number;
	readonly 'paymentTermName'?: string;
	'printedNote'?: string;
	'purchaseOrderNumber'?: string;
	'requestedDeliveryDate'?: string;
	'shippingAddress'?: HeadlessCommerceAdminOrder_v1_0_ShippingAddress;
	'shippingAddressId'?: number;
	'shippingAmount'?: number;
	'shippingAmountFormatted'?: string;
	'shippingAmountValue'?: number;
	'shippingDiscountAmount'?: number;
	'shippingDiscountAmountFormatted'?: string;
	'shippingDiscountAmountValue'?: number;
	'shippingDiscountPercentageLevel1'?: number;
	'shippingDiscountPercentageLevel1WithTaxAmount'?: number;
	'shippingDiscountPercentageLevel2'?: number;
	'shippingDiscountPercentageLevel2WithTaxAmount'?: number;
	'shippingDiscountPercentageLevel3'?: number;
	'shippingDiscountPercentageLevel3WithTaxAmount'?: number;
	'shippingDiscountPercentageLevel4'?: number;
	'shippingDiscountPercentageLevel4WithTaxAmount'?: number;
	'shippingDiscountWithTaxAmount'?: number;
	'shippingDiscountWithTaxAmountFormatted'?: string;
	'shippingMethod'?: string;
	'shippingOption'?: string;
	'shippingWithTaxAmount'?: number;
	'shippingWithTaxAmountFormatted'?: string;
	'shippingWithTaxAmountValue'?: number;
	'subtotal'?: number;
	readonly 'subtotalAmount'?: number;
	'subtotalDiscountAmount'?: number;
	'subtotalDiscountAmountFormatted'?: string;
	'subtotalDiscountPercentageLevel1'?: number;
	'subtotalDiscountPercentageLevel1WithTaxAmount'?: number;
	'subtotalDiscountPercentageLevel2'?: number;
	'subtotalDiscountPercentageLevel2WithTaxAmount'?: number;
	'subtotalDiscountPercentageLevel3'?: number;
	'subtotalDiscountPercentageLevel3WithTaxAmount'?: number;
	'subtotalDiscountPercentageLevel4'?: number;
	'subtotalDiscountPercentageLevel4WithTaxAmount'?: number;
	'subtotalDiscountWithTaxAmount'?: number;
	'subtotalDiscountWithTaxAmountFormatted'?: string;
	'subtotalFormatted'?: string;
	'subtotalWithTaxAmount'?: number;
	'subtotalWithTaxAmountFormatted'?: string;
	readonly 'subtotalWithTaxAmountValue'?: number;
	'taxAmount'?: number;
	'taxAmountFormatted'?: string;
	'taxAmountValue'?: number;
	'total'?: number;
	readonly 'totalAmount'?: number;
	'totalDiscountAmount'?: number;
	'totalDiscountAmountFormatted'?: string;
	'totalDiscountAmountValue'?: number;
	'totalDiscountPercentageLevel1'?: number;
	'totalDiscountPercentageLevel1WithTaxAmount'?: number;
	'totalDiscountPercentageLevel2'?: number;
	'totalDiscountPercentageLevel2WithTaxAmount'?: number;
	'totalDiscountPercentageLevel3'?: number;
	'totalDiscountPercentageLevel3WithTaxAmount'?: number;
	'totalDiscountPercentageLevel4'?: number;
	'totalDiscountPercentageLevel4WithTaxAmount'?: number;
	'totalDiscountWithTaxAmount'?: number;
	'totalDiscountWithTaxAmountFormatted'?: string;
	'totalDiscountWithTaxAmountValue'?: number;
	'totalFormatted'?: string;
	'totalWithTaxAmount'?: number;
	'totalWithTaxAmountFormatted'?: string;
	readonly 'totalWithTaxAmountValue'?: number;
	'transactionId'?: string;
	'workflowStatusInfo'?: HeadlessCommerceAdminOrder_v1_0_Status;
	readonly 'x-class-name'?: string;
};
