/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type {HeadlessCommerceAdminCatalog_v1_0_Attachment} from './HeadlessCommerceAdminCatalog_v1_0_Attachment';
import type {HeadlessCommerceAdminCatalog_v1_0_Catalog} from './HeadlessCommerceAdminCatalog_v1_0_Catalog';
import type {HeadlessCommerceAdminCatalog_v1_0_Category} from './HeadlessCommerceAdminCatalog_v1_0_Category';
import type {HeadlessCommerceAdminCatalog_v1_0_CustomField} from './HeadlessCommerceAdminCatalog_v1_0_CustomField';
import type {HeadlessCommerceAdminCatalog_v1_0_Diagram} from './HeadlessCommerceAdminCatalog_v1_0_Diagram';
import type {HeadlessCommerceAdminCatalog_v1_0_LinkedProduct} from './HeadlessCommerceAdminCatalog_v1_0_LinkedProduct';
import type {HeadlessCommerceAdminCatalog_v1_0_MappedProduct} from './HeadlessCommerceAdminCatalog_v1_0_MappedProduct';
import type {HeadlessCommerceAdminCatalog_v1_0_Pin} from './HeadlessCommerceAdminCatalog_v1_0_Pin';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductAccountGroup} from './HeadlessCommerceAdminCatalog_v1_0_ProductAccountGroup';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductChannel} from './HeadlessCommerceAdminCatalog_v1_0_ProductChannel';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductConfiguration} from './HeadlessCommerceAdminCatalog_v1_0_ProductConfiguration';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductOption} from './HeadlessCommerceAdminCatalog_v1_0_ProductOption';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductShippingConfiguration} from './HeadlessCommerceAdminCatalog_v1_0_ProductShippingConfiguration';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductSpecification} from './HeadlessCommerceAdminCatalog_v1_0_ProductSpecification';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductSubscriptionConfiguration} from './HeadlessCommerceAdminCatalog_v1_0_ProductSubscriptionConfiguration';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductTaxConfiguration} from './HeadlessCommerceAdminCatalog_v1_0_ProductTaxConfiguration';
import type {HeadlessCommerceAdminCatalog_v1_0_ProductVirtualSettings} from './HeadlessCommerceAdminCatalog_v1_0_ProductVirtualSettings';
import type {HeadlessCommerceAdminCatalog_v1_0_RelatedProduct} from './HeadlessCommerceAdminCatalog_v1_0_RelatedProduct';
import type {HeadlessCommerceAdminCatalog_v1_0_Sku} from './HeadlessCommerceAdminCatalog_v1_0_Sku';
import type {HeadlessCommerceAdminCatalog_v1_0_Status} from './HeadlessCommerceAdminCatalog_v1_0_Status';
export type HeadlessCommerceAdminCatalog_v1_0_Product = {
	readonly 'actions'?: Record<string, Record<string, string>>;
	'active': boolean;
	'attachments'?: Array<HeadlessCommerceAdminCatalog_v1_0_Attachment>;
	'catalog'?: HeadlessCommerceAdminCatalog_v1_0_Catalog;
	'catalogId': number;
	'categories'?: Array<HeadlessCommerceAdminCatalog_v1_0_Category>;
	'createDate'?: string;
	'customFields'?: Array<HeadlessCommerceAdminCatalog_v1_0_CustomField>;
	'defaultSku'?: string;
	'description'?: Record<string, string>;
	'diagram'?: HeadlessCommerceAdminCatalog_v1_0_Diagram;
	'displayDate'?: string;
	'expando'?: Record<string, Record<string, any>>;
	'expirationDate'?: string;
	'externalReferenceCode'?: string;
	readonly 'id'?: number;
	'images'?: Array<HeadlessCommerceAdminCatalog_v1_0_Attachment>;
	'linkedProducts'?: Array<HeadlessCommerceAdminCatalog_v1_0_LinkedProduct>;
	'mappedProducts'?: Array<HeadlessCommerceAdminCatalog_v1_0_MappedProduct>;
	'metaDescription'?: Record<string, string>;
	'metaKeyword'?: Record<string, string>;
	'metaTitle'?: Record<string, string>;
	'modifiedDate'?: string;
	'name': Record<string, string>;
	'neverExpire'?: boolean;
	'pins'?: Array<HeadlessCommerceAdminCatalog_v1_0_Pin>;
	'productAccountGroupFilter'?: boolean;
	'productAccountGroups'?: Array<HeadlessCommerceAdminCatalog_v1_0_ProductAccountGroup>;
	'productChannelFilter'?: boolean;
	'productChannels'?: Array<HeadlessCommerceAdminCatalog_v1_0_ProductChannel>;
	'productConfiguration'?: HeadlessCommerceAdminCatalog_v1_0_ProductConfiguration;
	readonly 'productId'?: number;
	'productOptions'?: Array<HeadlessCommerceAdminCatalog_v1_0_ProductOption>;
	'productSpecifications'?: Array<HeadlessCommerceAdminCatalog_v1_0_ProductSpecification>;
	'productStatus'?: number;
	'productType': string;
	readonly 'productTypeI18n'?: string;
	'productVirtualSettings'?: HeadlessCommerceAdminCatalog_v1_0_ProductVirtualSettings;
	'relatedProducts'?: Array<HeadlessCommerceAdminCatalog_v1_0_RelatedProduct>;
	'shippingConfiguration'?: HeadlessCommerceAdminCatalog_v1_0_ProductShippingConfiguration;
	'shortDescription'?: Record<string, string>;
	readonly 'skuFormatted'?: string;
	'skus'?: Array<HeadlessCommerceAdminCatalog_v1_0_Sku>;
	'subscriptionConfiguration'?: HeadlessCommerceAdminCatalog_v1_0_ProductSubscriptionConfiguration;
	'tags'?: Array<string>;
	'taxConfiguration'?: HeadlessCommerceAdminCatalog_v1_0_ProductTaxConfiguration;
	readonly 'thumbnail'?: string;
	'urls'?: Record<string, string>;
	readonly 'version'?: number;
	'workflowStatusInfo'?: HeadlessCommerceAdminCatalog_v1_0_Status;
	readonly 'x-class-name'?: string;
};
