configurations {
	portalTestSnapshot {
		exclude group: "com.liferay.portal", module: "com.liferay.portal.impl"
		exclude group: "com.liferay.portal", module: "com.liferay.portal.kernel"
	}
}

dependencies {
	compileInclude group: "com.liferay", name: "com.liferay.portal.tools.bundle.support", version: "3.7.5"

	implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.16.1"
	implementation group: "org.slf4j", name: "slf4j-api", version: "1.7.26"
}

updateFileVersions {
	match(/name: "com\.liferay\.resource\.util", version: "(\d.+)"/, "../release-util/build.gradle")
	match(/name: "com\.liferay\.resource\.util", version: "(\d.+)"/, "../../sdk/gradle-plugins-workspace/build.gradle")
}