/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { PageElement } from './PageElement';
import type { PageRule } from './PageRule';
import type { Settings } from './Settings';
/**
 * Represent a definition of a Page.
 */
export type PageDefinition = {
    /**
     * The page's page element.
     */
    pageElement?: PageElement;
    /**
     * A list of the page rules this page has.
     */
    pageRules?: Array<PageRule>;
    /**
     * The page's settings.
     */
    settings?: Settings;
    /**
     * The version of the JSON generated by page definition.
     */
    version?: number;
};

