/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type {HeadlessDelivery_v1_0_PageElement} from './HeadlessDelivery_v1_0_PageElement';
import type {HeadlessDelivery_v1_0_PageRule} from './HeadlessDelivery_v1_0_PageRule';
import type {HeadlessDelivery_v1_0_Settings} from './HeadlessDelivery_v1_0_Settings';

/**
 * Optional field with the structure of all the elements of the page. Can be embedded with nestedFields when retrieving the collection of site pages. When retrieving a single site page, it will automatically be included.
 */
export type HeadlessDelivery_v1_0_PageDefinition = {
	'pageElement'?: HeadlessDelivery_v1_0_PageElement;

	/**
	 * A list of the page rules this page has.
	 */
	'pageRules'?: Array<HeadlessDelivery_v1_0_PageRule>;
	'settings'?: HeadlessDelivery_v1_0_Settings;

	/**
	 * The version of the JSON generated by page definition.
	 */
	'version'?: number;
	readonly 'x-class-name'?: string;
};
