/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type {HeadlessAdminContent_v1_0_PageElement} from './HeadlessAdminContent_v1_0_PageElement';
import type {HeadlessAdminContent_v1_0_PageRule} from './HeadlessAdminContent_v1_0_PageRule';
import type {HeadlessAdminContent_v1_0_Settings} from './HeadlessAdminContent_v1_0_Settings';
export type HeadlessAdminContent_v1_0_PageDefinition = {
	'pageElement'?: HeadlessAdminContent_v1_0_PageElement;

	/**
	 * A list of the page rules this page has.
	 */
	'pageRules'?: Array<HeadlessAdminContent_v1_0_PageRule>;
	'settings'?: HeadlessAdminContent_v1_0_Settings;

	/**
	 * The version of the JSON generated by page definition.
	 */
	'version'?: number;
	readonly 'x-class-name'?: string;
};
