/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Account } from './Account';
import type { BillingAddress } from './BillingAddress';
import type { Channel } from './Channel';
import type { OrderItem } from './OrderItem';
import type { ShippingAddress } from './ShippingAddress';
import type { Status } from './Status';
export type Order = {
    readonly account?: Account;
    accountExternalReferenceCode?: string;
    accountId?: number;
    readonly actions?: Record<string, Record<string, string>>;
    advanceStatus?: string;
    billingAddress?: BillingAddress;
    billingAddressId?: number;
    readonly channel?: Channel;
    channelExternalReferenceCode?: string;
    channelId: number;
    couponCode?: string;
    createDate?: string;
    creatorEmailAddress?: string;
    currencyCode: string;
    customFields?: Record<string, any>;
    readonly deliveryTermDescription?: string;
    deliveryTermId?: number;
    readonly deliveryTermName?: string;
    externalReferenceCode?: string;
    id?: number;
    lastPriceUpdateDate?: string;
    modifiedDate?: string;
    orderDate?: string;
    orderItems?: Array<OrderItem>;
    orderStatus?: number;
    readonly orderStatusInfo?: Status;
    orderTypeExternalReferenceCode?: string;
    orderTypeId?: number;
    paymentMethod?: string;
    paymentStatus?: number;
    readonly paymentStatusInfo?: Status;
    readonly paymentTermDescription?: string;
    paymentTermId?: number;
    readonly paymentTermName?: string;
    printedNote?: string;
    purchaseOrderNumber?: string;
    requestedDeliveryDate?: string;
    shippingAddress?: ShippingAddress;
    shippingAddressId?: number;
    shippingAmount?: number;
    shippingAmountFormatted?: string;
    shippingAmountValue?: number;
    shippingDiscountAmount?: number;
    shippingDiscountAmountFormatted?: string;
    shippingDiscountAmountValue?: number;
    shippingDiscountPercentageLevel1?: number;
    shippingDiscountPercentageLevel1WithTaxAmount?: number;
    shippingDiscountPercentageLevel2?: number;
    shippingDiscountPercentageLevel2WithTaxAmount?: number;
    shippingDiscountPercentageLevel3?: number;
    shippingDiscountPercentageLevel3WithTaxAmount?: number;
    shippingDiscountPercentageLevel4?: number;
    shippingDiscountPercentageLevel4WithTaxAmount?: number;
    shippingDiscountWithTaxAmount?: number;
    shippingDiscountWithTaxAmountFormatted?: string;
    shippingMethod?: string;
    shippingOption?: string;
    shippingWithTaxAmount?: number;
    shippingWithTaxAmountFormatted?: string;
    shippingWithTaxAmountValue?: number;
    subtotal?: number;
    readonly subtotalAmount?: number;
    subtotalDiscountAmount?: number;
    subtotalDiscountAmountFormatted?: string;
    subtotalDiscountPercentageLevel1?: number;
    subtotalDiscountPercentageLevel1WithTaxAmount?: number;
    subtotalDiscountPercentageLevel2?: number;
    subtotalDiscountPercentageLevel2WithTaxAmount?: number;
    subtotalDiscountPercentageLevel3?: number;
    subtotalDiscountPercentageLevel3WithTaxAmount?: number;
    subtotalDiscountPercentageLevel4?: number;
    subtotalDiscountPercentageLevel4WithTaxAmount?: number;
    subtotalDiscountWithTaxAmount?: number;
    subtotalDiscountWithTaxAmountFormatted?: string;
    subtotalFormatted?: string;
    subtotalWithTaxAmount?: number;
    subtotalWithTaxAmountFormatted?: string;
    readonly subtotalWithTaxAmountValue?: number;
    taxAmount?: number;
    taxAmountFormatted?: string;
    taxAmountValue?: number;
    total?: number;
    readonly totalAmount?: number;
    totalDiscountAmount?: number;
    totalDiscountAmountFormatted?: string;
    totalDiscountAmountValue?: number;
    totalDiscountPercentageLevel1?: number;
    totalDiscountPercentageLevel1WithTaxAmount?: number;
    totalDiscountPercentageLevel2?: number;
    totalDiscountPercentageLevel2WithTaxAmount?: number;
    totalDiscountPercentageLevel3?: number;
    totalDiscountPercentageLevel3WithTaxAmount?: number;
    totalDiscountPercentageLevel4?: number;
    totalDiscountPercentageLevel4WithTaxAmount?: number;
    totalDiscountWithTaxAmount?: number;
    totalDiscountWithTaxAmountFormatted?: string;
    totalDiscountWithTaxAmountValue?: number;
    totalFormatted?: string;
    totalWithTaxAmount?: number;
    totalWithTaxAmountFormatted?: string;
    readonly totalWithTaxAmountValue?: number;
    transactionId?: string;
    readonly workflowStatusInfo?: Status;
};

