ext.expectedContentStrings = [
	'"externalReferenceCode" : "External Reference Code"',
	'"membershipType" : "open"',
	'"name" : "Site Name"',
	'"parentSiteKey" : "Parent Site Name"',
	'"templateKey" : "Sample Template Key"',
	'"templateType" : "Sample Template Type"',
]
ext.expectedFilePath = "site-initializer/site-initializer.json"

apply from: "./_baseFileContentTestCase.gradle"