jobs:
    publish-liferay-sample-workspace:
        secrets: inherit
        uses: ./.github/workflows/ci-publish-workspace.yaml
        with:
            workspace-name: liferay-sample-workspace
name: CI Publish liferay-sample-workspace
on:
    push:
        branches:
            - LPS-198630-TECHNICAL-TASK-v0-ticket-workspace-ant-task
        paths:
            - workspaces/liferay-sample-workspace/**