env:
    WORKSPACE_NAME: liferay-ticket-workspace
jobs:
    publish-liferay-workspace:
        secrets: inherit
        uses: ./.github/workflows/ci-publish-workspaces.yaml
        with:
            workspace-name: $WORKSPACE_NAME
name: CI Publish $WORKSPACE_NAME
on:
    push:
        branches:
            - LPS-198630-TECHNICAL-TASK-v0-ticket-workspace-ant-task
        paths:
            - workspaces/$WORKSPACE_NAME/**