name: Sync liferay-portal fork

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

jobs:
  sync_liferay_portal:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.repository}}
      - run: gh repo sync ${{github.repository}} --source liferay/liferay-portal --branch master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
